added terraform plan support

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -43,3 +43,9 @@ jobs:
       id: validate
       if: (success() || failure())
       run: terraform validate
+    # Run a terraform plan
+    # Run even if formatting fails
+    - name: Terraform plan
+      id: plan
+      if: (success() || failure())
+      run: terraform plan
